version: 0.2

phases:
  install:
    commands:
      - echo installing NGINX
      - sudo yum update
      - sudo yum install nginx -y
  build:
    commands:
      - echo Build started on `date`
      - cp index.html /usr/share/nginx/html/
  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - /usr/share/nginx/html/index.html
